### ISSUE TITLE
How to access sample service endpoints for non-local deployments

### ISSUE THREAD

**Issue by bcraun** [Azure/servicefabric-samples#10]
Can you provide guidance on how to access the web service endpoints in the samples when deployed in a non-local cluster? I've drilled down to view the replica address as was described in another issue, but the IPs are non-routable (10.0.0.x). I've tried to use the cluster's public URI with the replica address port shown in SF Explorer with no luck.

**Comment by vturecek** [comment]
There isn't really anything special about hosting a stateless web service on Service Fabric: you have a process running that is listening on some endpoint. So it's just a matter of knowing what that endpoint is  (http://IP:port/applicationpath) and making sure the nodes are accessible. 

If you have a cluster on Azure, on thing to look for is to make sure you have an instance of your web service on each node that the Azure Load Balancer is sending requests to. In the simplest case (with no Service Fabric placement constraints), that means having an instance of the web service on every node, because the Azure LB will round-robin requests to each one. To make sure an instance is active on every node, you can set the instance count of the service to "-1".

**Comment by bcraun** [comment]
I figured it out. I now see that one must explicitly open ports that match
the service manifest. Makes sense, but wasn't apparent the first time I
created a cluster.
